# run github actions

name: test

on:
  push:

defaults:
  run:
    shell: bash
jobs:
  test-read-mdcint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install gfortran
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install pytest for unit test
        run: |
          python -m pip install pytest
      - name: Run unittest
        run: |
          pytest
